---
micronaut:
  application:
    name: player-rx
    pref-file : prefs.json
    res-library-file : res-library-file.yaml
    legacy-pref-file : prefs.properties
  server:
    port: 9000
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled : true
        paths :
          - "classpath:public"
          - "file:${user.home}/.at/player/public"
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:~/.at/player-rx/db/player-rx.db;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
  default:
    entity-scan:
      packages: 'me.antoniocaccamo.player.rx.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true