name: player-rx CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name : gradle build
      uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with:
        args: build -x test

    - name : gradle sonarqube
      uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with:
        args: sonarqube -x test
